name: first-action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: |
          echo "Hello Action"
          echo "Hello GitHub"
          
      - name: print goodbye
        run: echo "goodbye"
